### ISSUE TITLE
Keepalived doesn't execute any notify or smtp_altert from Backup to Fault state

### ISSUE THREAD

**Issue by silou** [acassen/keepalived#101]
Hello,

We are currently seeing the following problem on version 1.2.7 RHEL6 RPM (also tested with my own RPM version 1.2.13).

"notify", "notify_fault" and "smtp_alert" doesn't fire when Keepalived is in Backup state and the vrrp_script fail. We can see in the log: Keepalived_vrrp[29331]: VRRP_Script(check_mysql) failed but nothing happen.

I have even tested by using the splitted version of "notify_*" instead of "notify" (doesn't work also).

This is really important for us, we use notify to track status of VRRP and we discover that presumed "Backup" instance is actually in "FAULT" state only when you switchover role (server01 to server02 for example).

Thanks for your help on this problem.
###### 

Here is my configuration : 

! Configuration File for keepalived

global_defs {
   notification_email {
    xx@yy.com
   }
   notification_email_from server01
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
   router_id server01

}

vrrp_script check_mysql {
    script "/root/mysql_keepalived.check"
    interval 3
        rise 3
        fall 3
    #weight 2
}

vrrp_instance VI_1 {
    state BACKUP
    nopreempt
    interface eth2
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        10.120.10.80/16 dev eth2 label eth2:mysql
    }
    #track_interface {
    #    eth0
    #}

   track_script {
        check_mysql
   }

   notify_master "/root/master.sh"
   notify_backup "/root/backup.sh"
   notify_fault "/root/faulty.sh"
   notify "/root/keepalived_update_status"
   smtp_alert
}

Example Faulty.sh:
# !/bin/bash

echo "`date` - i am faulty" >> /tmp/keepalived_log

**Comment by aaonline** [comment]
Is this fixed, I am seeing this issue again in RHEL 7.0 with keepalived 1.2.13 RPM

**Comment by nvx** [comment]
Looking at the commits that contain the fixes it appears to only be in the tags v1.2.14 v1.2.15 v1.2.16, so unless the fix has been backported in the RPM I would expect 1.2.13 to still have this issue.

**Comment by aaonline** [comment]
Oh.. 
Any chance I get rpm for 1.2.15 or higher for rhel7. 
The latest 1.2.16 tar install is also not working on rhel7 




        Sent by Outlook for Android

	_____________________________

From:NV

Subject:Re: [keepalived] Keepalived doesn't execute any notify or smtp_altert from Backup to Fault state (#101)

To:acassen/keepalived

Cc:aaonline





 
 
  

Looking at the commits that contain the fixes it appears to only be in the tags v1.2.14 v1.2.15 v1.2.16, so unless the fix has been backported in the RPM I would expect 1.2.13 to still have this issue.

**Comment by acassen** [comment]
I am not back-porting fix to previous release... make pressure over RH to get last release into their stuff... Or provide information on -devel mailing list in order to get assistance to make it built on your plateform.

**Comment by rohara** [comment]
On Wed, May 06, 2015 at 11:27:57PM -0700, aaonline wrote:
> Oh.. 
> Any chance I get rpm for 1.2.15 or higher for rhel7. 

I am planning to put the latest release in rhel-7.2.

> The latest 1.2.16 tar install is also not working on rhel7 

What problems are you seeing with 1.2.16 on rhel7?

Ryan

**Comment by aaonline** [comment]
Hi Ryan, 
Appreciate your help. 
Actually,  when I install keepalived on RHEL 7.0, there is a sample configuration file created in /etc/keepalived/keepalived.conf.  Now when I provide  a check script in it,  somehow from the check script I am only able to create a new file for status logging in /var/run folder and not anywhere else.  I have even tried tons of combination and I am unable to either run any other script from check.sh.  Same for notify.sh.  However it works on Ubuntu 14.04 pretty much. 
I am able to call other scripts from shell and check and notify have 777 rights. 
The issue is check.sh does not work like a shell script and runs like under some restrictions. 
Any suggestions... 





        Sent by Outlook for Android

	_____________________________

From:rohara

Subject:Re: [keepalived] Keepalived doesn't execute any notify or smtp_altert from Backup to Fault state (#101)

To:acassen/keepalived

Cc:aaonline





 
 
  On Wed, May 06, 2015 at 11:27:57PM -0700, aaonline wrote:
  
 > Oh.. 
  
 > Any chance I get rpm for 1.2.15 or higher for rhel7. 
  
 
  
 I am planning to put the latest release in rhel-7.2.
  
 
  
 > The latest 1.2.16 tar install is also not working on rhel7 
  
 
  
 What problems are you seeing with 1.2.16 on rhel7?
  
 
  
 Ryan

**Comment by aaonline** [comment]
Hi Ryan,
Just some workaroun,
this issue happens when I start the service as
#service keepalived start
but when I start the service as #keepalived -D -d
I DO NOT see any errors, all works smooth...
Any suggestions ?

RegardsAbhi








Date: Sat, 9 May 2015 19:15:43 +0000

**Comment by raulp** [comment]
same here :) on centos 7.1, if we start keepalived with systemctl it does not run any scripts, so no IP migration. If i run it manually 
```keepalived -S 7 -f /etc/keepalived/keepalived.conf -D -n```
works like a charm

**Comment by rohara** [comment]
Is SELinux enabled? If so, please check your audit logs for SELinux AVCs.

**Comment by raulp** [comment]
@rohara , yes, indeed was enabled.
Will do a test later today or tomorrow with it disabled.

**Comment by rohara** [comment]
@raulp, Thanks for the information.

The proposed solution for RHEL variants is to have a directory (/usr/libexec/keepalived) where users will place any/all scripts that keepalived will execute, then have the SELinux policy modified such that keepalived has permission to execute scripts in this directory. I've update keepalived packaging for Fedora and recent RHEL releases to create this directory, but I am not sure of the status in Centos. I am also not sure if the selinux policy has been updated yet. I'll check into that.

**Comment by raulp** [comment]
@rohara thanks ! that sounds good to me. i'll go ahead and do that test tonight and let you know for sure if selinux was the problem in my case. But i suspect so :)

**Comment by ebarault** [comment]
this thread is quite old, but i had a similar issue. 

- SELinux was not activated
- notify_master script was executed but with some restrictions (i am lauching some `aws cli` commands that were not executed, but some `echo "foo" >> bar.log` were doing ok  

it happens i had the option `--dont-fork` in my startup script

> solution was to **remove this option**

**Comment by edgewater9** [comment]
Hi, I am still having this issue.  Just as @raulp had said, keepalived executes all the commands included in the notify script if I run the keepalived program in foreground (I am launching remote ssh command over internal network).  However, it would only work partially if I run the keepalived program as a service.  
@ebarault  which environment variables were missing from the root user?  I had made sure that the same environment variables in the foreground command are also made available when keepalived service is running, but the same problem still exists.

**Comment by pqarmitage** [comment]
In respect of the original issue that was raised:
  
In the master branch of keepalived:
   "notify" and "notify_fault" scripts will run when the instance transitions to fault state
   "smtp_alert" will not execute

On the beta branch:
    "notify" and "notify_fault" scripts will run when the instance transitions to fault state
    "smtp_alert" will execute if `email_faults` is configured in the global_defs section of the configuration.

The reason for only sending the fault emails if `email_faults` is configured is to maintain backwards compatibility with earlier versions of keepalived, although if there is a general feeling the fault emails should be sent be default, then I would be quite happy to change it so that fault emails are sent be default, and I would add `no_email_faults` to turn the functionality off.

**Comment by edgewater9** [comment]
@pqarmitage Thank you for responding to my inquiry.  I found that the notify_master does execute script, and all simple commands (such as writing a message to a file, etc.) in the script program are executed, but it simply would not execute a remote shell command via SSH to other host.  I wonder if this is a technical limitation by design?

**Comment by pqarmitage** [comment]
@edgewater9 You could try adding the `-E logfile` option to the ssh command to see if that logs why it isn't working.

On my systems I never allow root login via ssh, and of course keepalived is running as root. This means that login credentials will have to be supplied, which may not be correctly set up. It might work if you specify the `username` option on the notify configuration line (see doc/keepalived.doc.SYNOPSIS in the source tree).

**Comment by edgewater9** [comment]
@pqarmitage  I am using other user account for remote login via "sudo -u someadmin ssh x.x.x.x /home/someadmin/runscript.sh" 
Interestingly, if I run this command either directly or run keepalived in foreground, the command works.  It only would not work when keepalived is running as a service.  SELinux is also disabled.  
I just tried with -E logfile option, but it returned with an error message: invalid option -- 'E'
I am running keepalived v1.2.13  
Am I running too outdated version of keepalived?

**Comment by pqarmitage** [comment]
@edgewater9 I have found that if I have a configuration line:
`notify_master "sudo -u someadmin ssh x.x.x.x /home/someadmin/runscript.sh"`
it doesn't work.

If I create a script `/tmp/rem_ssh.sh` with execute permissions as
```
#!/bin/bash
sudo -u someadmin ssh x.x.x.x /home/someadmin/runscript.sh
```
and change the configuration line to:
`notify_master "/tmp/rem_ssh.sh"`
then it does work.

Not quite sure why yet.

**Comment by pqarmitage** [comment]
@edgewater9 

Further testing with v1.4.0 shows:
`notify_master "echo ..."` doesn't work - error `Script sudo cannot be accessed - No such file or directory` in syslog
`notify_master "/bin/echo ..."` does work

`notify_master "sudo -u someadmin ssh x.x.x.x /home/someadmin/runscript.sh"`
gives error
`Script sudo cannot be accessed - No such file or directory`
in the syslog output file.

`notify_master "/usr/bin/sudo -u someadmin ssh x.x.x.x /home/someadmin/runscript.sh"` works.

Between v1.2.13 and v1.4.0 I have significantly changed the code for handling notify scripts, so it would be worth upgrading to a recent version. In addition to that, there have been many enhancements and fixes since v1.2.13, amounting to some 1300 non-merge commits, so yes, it is well worth upgrading to v1.4.0.

**Comment by pqarmitage** [comment]
@edgewater9 I've investigated this further and discover that the problem in v1.4.0 is due to a bug in the code relating to path resolution. In particular, if the executable is not a fully qualified name (in other words it is resolved via the path), and there is a '/' character amongst the parameters, then the path to the executable would not be resolved.

Commit d381daa resolves this problem.

**Comment by tuyendd25** [comment]
Hello,

KeepAlived is really a good product, but this problem is still in the way.

Is there anything we can do please?

**Comment by pqarmitage** [comment]
@tuyendd25 If you upgrade to the current version of keepalived, i.e. v2.0.4, or better still the HEAD of the master branch at github, then it does execute notify scritps and SMTP alerts when transitioning from BACKUP to FAULT.

**Comment by pguser12** [comment]
> Is SELinux enabled? If so, please check your audit logs for SELinux AVCs.

My SELinux was enabled; changinf it to permissive worked for me; thanks!!
