### ISSUE TITLE
Can't compile under centos7

### ISSUE THREAD

**Issue by jsfrerot** [acassen/keepalived#1464]
When compiling keepalived 2.0.19 on centos 7 I get the following errors:

1- + CONFIG_OPTS=
+ '@DEBUG_TRUE@CONFIG_OPTS= --enable-debug'
/var/tmp/rpm-tmp.iSxVrn: line 30: @DEBUG_TRUE@CONFIG_OPTS= --enable-debug: command not found
error: Bad exit status from /var/tmp/rpm-tmp.iSxVrn (%build)

Had to remove @DEBUG_TRUE@CONFIG_OPTS="$CONFIG_OPTS --enable-debug" from keepalived.spec.in

2- + CONFIG_OPTS=
+ CONFIG_OPTS=' --disable-nftables'
+ CONFIG_OPTS=' --disable-nftables --disable-libipset'
+ '@LIBXTABLES_DYNAMIC_TRUE@CONFIG_OPTS= --disable-nftables --disable-libipset --enable-libxtables-dynamic'
/var/tmp/rpm-tmp.fnXUPj: line 38: @LIBXTABLES_DYNAMIC_TRUE@CONFIG_OPTS= --disable-nftables --disable-libipset --enable-libxtables-dynamic: command not found
error: Bad exit status from /var/tmp/rpm-tmp.fnXUPj (%build)

Had to remove @LIBXTABLES_DYNAMIC_TRUE@CONFIG_OPTS="$CONFIG_OPTS --enable-libxtables-dynamic" from keepalived.spec.in

3- configure: error: enable-snmp-reply-v3-for-v2 requires enable-snmp-rfcv3 or enable-snmp-rfc
error: Bad exit status from /var/tmp/rpm-tmp.bv1O3e (%build)

Had to remove @SNMP_REPLY_V3_FOR_V2_FALSE@CONFIG_OPTS="$CONFIG_OPTS --disable-snmp-reply-v3-for-v2" from keepalived.spec.in

**Comment by pqarmitage** [comment]
Many thanks for reporting this.

1. From what I can see commit 844e197 broke this. I cannot generate this error with v2.0.19 without any subsequent commits. A new commit, b3c87c4, resolves the problem caused by commit 844e197.

2. This was resolved by commit 13b8e0c.

3. This was resolved by commit c8d2f14.

What is strange is that commits 13b8e0c and c8d2f14 were merged before 844e197.

If the problem isn't resolved, please reopen the issue.

**Comment by jsfrerot** [comment]
Hi, I've just test recompiling on centos 7 with tag 2.0.19 and I confirm the issue 2 and 3 are still present
