### ISSUE TITLE
keepalived 1.2.20 logs "unknown keyword"

### ISSUE THREAD

**Issue by rubenk** [acassen/keepalived#297]
The following config:
```
global_defs {
   router_id a1
}

static_ipaddress {
    192.168.10.10/32 dev eth0
}

virtual_server 192.168.10.10 23 {
    delay_loop 6
    lb_algo rr
    lb_kind TUN
    protocol TCP

    real_server 192.168.10.10 23 {
        weight 1
    }
}
```
logs:
```
Apr 16 22:56:14 ipvs1a Keepalived[2209]: Starting Keepalived v1.2.20 (04/16,2016)
Apr 16 22:56:14 ipvs1a Keepalived[2210]: Starting Healthcheck child process, pid=2212
Apr 16 22:56:14 ipvs1a Keepalived[2210]: Starting VRRP child process, pid=2213
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Netlink reflector reports IP 37.252.120.129 added
Apr 16 22:56:14 ipvs1a Keepalived_vrrp[2213]: Netlink reflector reports IP 37.252.120.129 added
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Registering Kernel netlink reflector
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Registering Kernel netlink command channel
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Unknown keyword '192.168.10.10/32'
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Unknown keyword '}'
Apr 16 22:56:14 ipvs1a Keepalived_vrrp[2213]: Registering Kernel netlink reflector
Apr 16 22:56:14 ipvs1a Keepalived_vrrp[2213]: Registering Kernel netlink command channel
Apr 16 22:56:14 ipvs1a Keepalived_vrrp[2213]: Registering gratuitous ARP shared channel
Apr 16 22:56:14 ipvs1a Keepalived_vrrp[2213]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 16 22:56:14 ipvs1a Keepalived_vrrp[2213]: Using LinkWatch kernel netlink reflector...
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Using LinkWatch kernel netlink reflector...
Apr 16 22:56:14 ipvs1a Keepalived_healthcheckers[2212]: Netlink reflector reports IP 192.168.10.10 added
```

It doesn't like the static_ipaddress part.
It does work however:

# ip a s dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:1a:4a:40:07:98 brd ff:ff:ff:ff:ff:ff
    inet 37.252.120.129/24 brd 37.252.120.255 scope global eth0
    inet 192.168.10.10/32 scope global eth0

**Comment by acassen** [comment]
hmm, because static_ipaddress might not be a shared keyword, only vrrp part handle it. This is the reason why you can see the ip address.

**Comment by Vayu** [comment]
I'm seeing the same warning message. Is it safe to ignore?

**Comment by pqarmitage** [comment]
I have a patch that resolves this problem that I should be able to submit this evening.

Whether it is safe to ignore the messages currently depends on whether your configuration is valid. If you are seeing the same configuration item reported for both Keepalived_vrrp and Keepalived_checkers, then you probably have a configuration error.

**Comment by Vayu** [comment]
More specifically, is it safe to ignore "Unknown keyword 'x.x.x.x/32'" coming from Keepalived_healthcheckers because of 'static_ipaddress' section.

**Comment by pqarmitage** [comment]
Yes, that's fine to ignore.

**Comment by notjoe** [comment]
I apologize if this is off-topic. Did something happen to the virtual_server_group declaration? 
Unknown keyword 'virtual_server_group' ? 

<included config file>
virtual_server_group httpj_group {
my.ip.number.one/32 8087
my.ip.number.two/32 8087
} 

 virtual_server group httpj_group {
        persistence_timeout 120
        delay_loop 15
        lb_algo wrr
        lb_kind DR
        protocol TCP
        real_server 10.0.0.25 8087 {
                weight 1
                        TCP_CHECK {
                        connect_timeout 5
                         }
                }
}

</included config file>

**Comment by pqarmitage** [comment]
This was resolved two days ago with commit 584ff2b.

This issue was not that the virtual_server_group declaration didn't work, but that the VRRP process didn't recognise the keyword. The change since v1.2.13 is that until v1.2.20 unknown keywords were silently ignored (which was a nightmare), but from v1.2.20 the vrrp and checker child processes reported keywords they didn't recognise.

Please report if problems still persist when using the later version from git.

**Comment by notjoe** [comment]
@pqarmitage Thanks for the update. I downloaded the 1.2.23 tgz from the main site and was still getting those errors. I'll clone the latest from here and see if I still encounter the same issue.

**Comment by notjoe** [comment]
I've cloned the repo and compiled versions 1.2.20 (1.2.19 failed to compile) through 1.2.23. They're  are all giving me the unknown keyword. If you need me to provide logs or anything just let me know. Even compiled the master branch and it is giving me the same error.

**Comment by pqarmitage** [comment]
The fix was implemented after the v1.2.23 release. You need to checkout master and try that. If you run keepalived -v you should get something like `Keepalived v1.2.23 (08/11,2016), git commit v1.2.23-64-g635fa1c`. The version string `Keepalived v1.2.23 (08/11,2016)` that you have shows you have v1.2.23 with no subsequent commits.
